services:
  postgres:
    container_name: container-pg
    image: pgvector/pgvector:pg17
    hostname: localhost
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./storage/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4:9.2
    depends_on:
      - postgres
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - ./storage/pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
